name: PlantUML Diagrams

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate diagrams
        uses: holowinski/plantuml-github-action@1.2021.1
        with:
          args: -v -tsvg diagrams/*.puml