name: PlantUML Diagrams

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install PlantUML
      run: sudo apt install plantuml

    - name: Generate diagrams
      run: plantuml *.plantuml

    - uses: actions/checkout@v4
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - name: Commit diagrams
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add **/*.png
        git commit -m "Automated diagram generation"
        git push origin main
      if: success()
